version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  App:
    level: INFO
    handlers: [console]
    propagate: no
  Reign:
    level: INFO
    handlers: [console]
    propagate: no
  Utils:
    level: INFO
    handlers: [console]
    propagate: no
  TelegramHandler:
    level: INFO
    handlers: [console]
    propagate: no
  StatsHandler:
    level: INFO
    handlers: [console]
    propagate: no