it:
  battle_a: "âš”ï¸âš”ï¸ *%s* sta per attaccare *%s* âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ *%s* sta per attaccare *%s*, del Regno di *%s* âš”ï¸âš”ï¸"
  attacker_won: "*%s* ha sottratto *%s* al Regno di *%s* ğŸ—¡"
  defender_won: "*%s* _ha resistito all'attacco_ di *%s* ğŸ›¡"
  defender_defeated: "Il Regno di %s Ã¨ stato sconfitto âœï¸"
  capitol_defeated: "*%s* ha conquistato *%s* e tutti suoi territori ğŸ—¡"
  remaining_territories: "%d regni rimanenti."
  the_winner_is: "ğŸ†ğŸ†ğŸ† *%s* HA VINTO LA GUERRA!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Che la guerra abbia inizio!!âš”ï¸ğŸ”µ"
  poll: "Con chi ti vuoi schierare?!"

en:
  battle_a: "âš”ï¸âš”ï¸ *%s* sta per attaccare *%s* âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ *%s* sta per attaccare *%s*, del Regno di *%s* âš”ï¸âš”ï¸"
  attacker_won: "*%s* ha sottratto *%s* al Regno di *%s* ğŸ—¡"
  defender_won: "*%s* _ha resistito all'attacco_ di *%s* ğŸ›¡"
  defender_defeated: "Il Regno di %s Ã¨ stato sconfitto âœï¸"
  capitol_defeated: "*%s* ha conquistato *%s* e tutti suoi territori ğŸ—¡"
  remaining_territories: "%d regni rimanenti."
  the_winner_is: "ğŸ†ğŸ†ğŸ† *%s* HA VINTO LA GUERRA!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Che la guerra abbia inizio!!âš”ï¸ğŸ”µ"
  poll: "Con chi ti vuoi schierare?!"
