it:
  battle_a: "âš”ï¸âš”ï¸ %s sta per attaccare %s âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ %s, del Regno di %s, sta per attaccare %s âš”ï¸âš”ï¸"
  battle_c: "âš”ï¸âš”ï¸ %s sta per attaccare %s, del Regno di %s âš”ï¸âš”ï¸"
  battle: "âš”ï¸âš”ï¸ %s, del Regno di %s, sta per attaccare %s, del Regno di %s âš”ï¸âš”ï¸"
  attacker_won: "*%s* ha conquistato *%s*. Ora il territorio di %s fa parte del *Regno di %s* ğŸ—¡"
  defender_won: "*%s* ha __resistito__ all'attacco di **%s** ğŸ›¡"
  defender_defeated: "Il Regno di %s Ã¨ stato sconfitto âœï¸"
  capitol_defeated: "*%s* ha conquistato *%s* e tutti i territori fanno ora parte del Rregno di *%s* ğŸ—¡"
  remaining_territories: "%d regni rimanenti."
  the_winner_is: "ğŸ†ğŸ†ğŸ† %s HA VINTO LA GUERRA!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Che la guerra abbia inizio!!âš”ï¸ğŸ”µ"
  poll: "Con chi ti vuoi schierare?!"

en:
  battle_a: "âš”ï¸âš”ï¸ %s is going to attack %s âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ %s, of the %s's empire, is going to attack %s âš”ï¸âš”ï¸"
  battle_c: "âš”ï¸âš”ï¸ %s is going to attack %s, of the %s's empire âš”ï¸âš”ï¸"
  battle: "âš”ï¸âš”ï¸ %s, f the %s's empire, is going to attack %s, of the %s's empire âš”ï¸âš”ï¸"
  attacker_won: "%s conquered %s. Now the %s territory is part of the %s' empire ğŸ—¡"
  defender_won: "%s resisted to the attack of %s ğŸ›¡"
  defender_defeated: "The empire %s has been defeated âœï¸"
  remaining_territories: "%d remaining empires."
  the_winner_is: "ğŸ†ğŸ†ğŸ† %s WON THE WAR!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Let's the War begin!!âš”ï¸ğŸ”µ"
  poll: "With whom do you want to allay?!"