it:
  battle_a: "âš”ï¸âš”ï¸ %s sta per attaccare %s âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ %s, dell'impero di %s, sta per attaccare %s âš”ï¸âš”ï¸"
  battle_c: "âš”ï¸âš”ï¸ %s sta per attaccare %s, dell'impero di %s âš”ï¸âš”ï¸"
  battle: "âš”ï¸âš”ï¸ %s, dell'impero di %s, sta per attaccare %s, dell'impero di %s âš”ï¸âš”ï¸"
  attacker_won: "%s ha conquistato %s ğŸ—¡"
  defender_won: "%s ha resistito all'attacco di %s ğŸ›¡"
  defender_defeated: "L'impero di %s Ã¨ stato sconfitto âœï¸"
  remaining_territories: "%d territori rimanenti."
  the_winner_is: "ğŸ†ğŸ†ğŸ† %s HA VINTO LA GUERRA!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Che la guerra abbia inizio!!âš”ï¸ğŸ”µ"

en:
  battle_a: "âš”ï¸âš”ï¸ %s is going to attack %s âš”ï¸âš”ï¸"
  battle_b: "âš”ï¸âš”ï¸ %s, of the %s's empire, is going to attack %s âš”ï¸âš”ï¸"
  battle_c: "âš”ï¸âš”ï¸ %s is going to attack %s, of the %s's empire âš”ï¸âš”ï¸"
  battle: "âš”ï¸âš”ï¸ %s, f the %s's empire, is going to attack %s, of the %s's empire âš”ï¸âš”ï¸"
  attacker_won: "%s conquered %s ğŸ—¡"
  defender_won: "%s resisted to the attack of %s ğŸ›¡"
  defender_defeated: "The empire %s has been defeated âœï¸"
  remaining_territories: "%d remaining territories."
  the_winner_is: "ğŸ†ğŸ†ğŸ† %s WON THE WAR!!! ğŸ†ğŸ†ğŸ†"
  start: "ğŸ”´âš”ï¸Let's the War begin!!âš”ï¸ğŸ”µ"